---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-helloworld: "secret/helloworld"
        vault.hashicorp.com/role: "myapp"
        vault.hashicorp.com/agent-inject-template-helloworld: |
          {{- with secret "secret/helloworld" -}}
          {{ range $name, $secret :=  .Data.data }}
          export {{$name}}={{ $secret }}
          {{ end }}
          {{- end }}      
      labels:
        app: webapp
    spec:
      serviceAccountName: app
      containers:
        - name: app
          image: ahmadoosh99/vault-try:v1
          imagePullPolicy: Always
          args: ["sh", "-c","source /vault/secrets/helloworld && npm start ${USERNAME} ${PASSWORD}"]
          ports:
          - containerPort: 3000
            protocol: TCP
          # env:
          #   - name: USERNAME
          #     value: 'username'
          #   - name: PASSWORD
          #     value: 'password'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app
  labels:
    app: webapp